name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: '20'

jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Prisma Client
      run: npm run prisma:generate
      
    - name: Build application
      run: npm run build
      env:
        SKIP_ENV_VALIDATION: true
        
    # Vercel Preview deployment
    - name: Deploy Preview to Vercel
      if: ${{ vars.PREVIEW_TARGET == 'vercel' }}
      uses: amondnet/vercel-action@v25
      id: vercel-preview
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Comment PR with preview URL
      if: ${{ vars.PREVIEW_TARGET == 'vercel' }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const url = '${{ steps.vercel-preview.outputs.preview-url }}';
          const comment = `🚀 Preview deployment is ready!\n\n🔗 Preview URL: ${url}`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });